language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci"
matrix:
  include:
    - rvm: 1.9.3
    - rvm: 2.0.0
    - rvm: ruby-head
    - rvm: rbx-19mode
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  allow_failures:
    - rvm: ruby-head     # Broken at this time, rvm issue on travis
    - rvm: rbx-19mode    # Broken at this time, yard/yardstick issue
    - rvm: jruby-19mode  # No fork(2) support, workaround planned
    - rvm: jruby-head    # No fork(2) support, workaround planned
notifications:
  irc:
    channels:
      - irc.freenode.org#mutant
    on_success: never
    on_failure: change
